name: acrordrdc
title: Adobe Acrobat Reader (WINE)
summary: Adobe Acrobat Reader is a pdf reader & Web services developed by Adobe Inc.
description: |
  Adobe Acrobat Reader DC software is the free global standard for reliably viewing, printing, and commenting on PDF documents.

  And now, it's connected to the Adobe Document Cloud − making it easier than ever to work across computers and mobile devices.

  It's the only PDF viewer that can open and interact with all types of PDF content, including forms and multimedia.
adopt-info: acrordrdc

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: [amd64, i386]
base: core18

plugs:
  wine-runtime-c20:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core20
  wine-7-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-stable-core20

environment:
  WINEARCH: "win32"
  WINEDLLOVERRIDES: "mscoree,mshtml="   # Prevent pop-ups about Wine Mono and Wine Gecko
  NO_AT_BRIDGE: "1"
  DISABLE_WAYLAND: "1" # Fix gtk decoration under wayland session
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc
  RUN_EXE: "C:/Program Files/Adobe/Acrobat Reader DC/Reader/AcroRd32.exe"

apps:
  acrordrdc:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    plugs:
      - cups-control
      - home
      - network
      - removable-media
      - opengl

  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  acrordrdc:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(curl 2>/dev/null -vs https://helpx.adobe.com/acrobat/release-note/release-notes-acrobat-reader.html | grep "continuous" | cut -d'"' -f5 | sed -n 2p | sed 's|(| |g;s|)| |g' | awk 'FNR == 10 {next} {print $4}')
      snapcraftctl set-version "20$ver"
      mkdir -p sommelier/hooks ; mv pre-install sommelier/hooks ; cp -R -p sommelier $SNAPCRAFT_PART_INSTALL
    stage:
      - sommelier
    build-packages:
      - curl

  # The sommelier script helps you snap Windows applications using Wine. It 
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/mmtrt/sommelier-core.git
    source-branch: "tmp-core20"

  fixup-url:
    after: [sommelier]
    plugin: nil
    override-build: |
      lver=$(curl 2>/dev/null -vs https://helpx.adobe.com/acrobat/release-note/release-notes-acrobat-reader.html | grep "continuous" | cut -d'"' -f5 | sed -n 2p | sed 's|(| |g;s|)| |g' | awk 'FNR == 10 {next} {print $4}' | tr -d '.')
      # Continuous installer 
      cver=$(curl 2>/dev/null -vs https://helpx.adobe.com/acrobat/release-note/release-notes-acrobat-reader.html | grep "dccontinuousmay2021" | sed 's|(| |g;s|)| |g' | awk 'FNR == 10 {next} {print $6}' | tr -d '.')
      # Patch pre-install file
      sed -i "s|XXX|$lver|g" ../../acrordrdc/install/sommelier/hooks/pre-install
      sed -i "s|YYY|$cver|g" ../../acrordrdc/install/sommelier/hooks/pre-install
